
# :::::::::::::::::::::::::::::::
# : DATA SOURCE
# :::::::::::::::::::::::::::::::
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)


# IDENTITY (ContextIdApplicationContextInitializer)
spring:
      application.name: "demo"
# Set here configurations for the database connection (our servers)
      datasource.url: "jdbc:mysql://127.0.0.1:3306/demodb"
      datasource.driver-class-name: "com.mysql.jdbc.Driver"
      datasource.username: "root"
      datasource.password: "toor"
# Specify the DBMS
      jpa.database : "MYSQL"
# Show or not log for each sql query
      jpa.show-sql : true
# Hibernate settings are prefixed with spring.jpa.hibernate.*
      jpa.hibernate.ddl-auto : "none"
      jpa.hibernate.dialect : "org.hibernate.dialect.MySQL5InnoDBDialect"
      jpa.hibernate.naming_strategy : "org.hibernate.cfg.ImprovedNamingStrategy"

#remove when when you want to uplaod a war 
logging.level.org.apache.http: "DEBUG"


#tomcat properties
#server.tomcat.max-threads:400


# JWT  Properties
#app.jwtSecret: SecretKey
#app.jwtExpirationMs: 86400000





